hw04
taaleksandra/nodejs-homeworks pull request #3
Opened 2023-09-01 11:46 UTC by taaleksandra

2023-09-02 00:23 UTC, RadziuMM requested changes

2023-09-02 00:23 UTC, RadziuMM commented on controller/auth.js
> +    const user = await User.findOne({ _id });
User jest już zwracany przez auth w req.user, nie ma potrzeby pobierać go 2 raz.

2023-09-02 00:23 UTC, RadziuMM commented on controller/auth.js
> +    const user = await User.findOne({ _id });
User jest już zwracany przez auth w req.user, nie ma potrzeby pobierać go 2 raz.

2023-09-02 00:23 UTC, RadziuMM commented on controller/contacts.js
> +    // const value = await responseSchema.validate(req.body);
zakometowany kod i nwm czemu usuwasz walidacje ???

2023-09-02 00:23 UTC, RadziuMM commented on middlewares/auth.js
> +    if (!user || err) {
tu jeszcze trzeba sprawdzić czy user.token jest taki sam jak token z req. Bo teraz możesz się wylogować i nadal sprawdzić starym tokenem /current

2023-09-04 09:29 UTC, taaleksandra commented on controller/auth.js
> +    const user = await User.findOne({ _id });
poprawione

2023-09-04 09:29 UTC, taaleksandra commented on controller/auth.js
> +    const user = await User.findOne({ _id });
poprawione

2023-09-04 09:32 UTC, taaleksandra commented on controller/contacts.js
> +    // const value = await responseSchema.validate(req.body);
Już poprawiłam. Walidacja wróciła

2023-09-04 09:32 UTC, taaleksandra commented on middlewares/auth.js
> +    if (!user || err) {
poprawione

2023-09-04 09:39 UTC, RadziuMM approved these changes

2023-09-08 07:09 UTC, merged